apiVersion: apps/v1
kind: Deployment
metadata:
  name: nks-wavecafe  # 🚀 Name of the Deployment
spec:
  replicas: 1  # 🚶 Number of desired replicas
  selector:
    matchLabels:
      app: cafe  # 🏷️ Selector to match pods with the label "app: cafe"
  template:
    metadata:
      labels:
        app: cafe  # 🏷️ Labels applied to pods created by this template
    spec:
      containers:
        - name: my-app-container  # 📦 Name of the container
          image: nextkodeschool/highway:latest  # 🐳 Docker image to use
          ports:
            - name: cafe-port  # 🌐 Name of the port
              containerPort: 80  # 🚪 Port that the container listens on
