apiVersion: apps/v1
kind: Deployment
metadata:
  name: nks-web
spec:
  replicas: 3

  selector:
    matchLabels:
      app: nks-web

  template:
    metadata:
      labels:
        app: nks-web

    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
