apiVersion: v1
kind: Service
metadata:
  name: nks-wavecafe  # ☕ Name of the Service
spec:
  selector:
    app: cafe  # 🏷️ Select pods with the label "app: cafe"
  ports:
    - protocol: TCP  # 🌐 Protocol for the port
      port: 80  # 🚪 Port on the Service
      targetPort: cafe-port  # 🚀 Port on the pods to forward traffic to
  type: NodePort  # 🏢 Expose the Service as a NodePort
