apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nks-web
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/nextkodeschook/ArgoCD.git

    targetRevision: main

    path: application

  destination:
    server: https://kubernetes.default.svc

    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
